//Ailment Action Types
export const ADD_AILMENT = "ADD_AILMENT";
export const REMOVE_AILMENT = "REMOVE_AILMENT";
export const ADD_STRAIN_TO_USER_SAVED = "ADD_STRAIN_TO_USER_SAVED";
export const REMOVE_STRAIN_FROM_USER_SAVED = "REMOVE_STRAIN_FROM_USER_SAVED";
